### ISSUE TITLE
Attempting to use the tool with no folder loaded results in exception.

### ISSUE THREAD

**Issue by MicahZoltu** [Zoltu/zoltu-jspm-atom#2]
```
TypeError: Arguments to path.join must be strings
  at f (path.js:178:13)
  at Object.filter (native)
  at Object.win32.join (path.js:183:38)
  at Object.module.exports.ZoltuJspm.pathToJspm (C:\Users\Micah\Source\zoltu-jspm-atom\lib\zoltu-jspm.coffee:80:15)
  at Object.module.exports.ZoltuJspm.executeJspm (C:\Users\Micah\Source\zoltu-jspm-atom\lib\zoltu-jspm.coffee:73:14)
  at Object.module.exports.ZoltuJspm.install (C:\Users\Micah\Source\zoltu-jspm-atom\lib\zoltu-jspm.coffee:62:4)
  at Object.module.exports.ZoltuJspm.confirm (C:\Users\Micah\Source\zoltu-jspm-atom\lib\zoltu-jspm.coffee:54:25)
  at atom-text-editor.subscriptions.add.atom.commands.add.core:confirm (C:\Users\Micah\Source\zoltu-jspm-atom\lib\zoltu-jspm.coffee:24:110)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\Micah\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:238:29)
  at C:\Users\Micah\AppData\Local\atom\app-0.192.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (C:\Users\Micah\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:519:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\Micah\AppData\Local\atom\app-0.192.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:354:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (C:\Users\Micah\AppData\Local\atom\app-0.192.0\resources\app\src\window-event-handler.js:180:20)
```

**Comment by MicahZoltu** [comment]
Fixed in 1de83a34b905420d78561c659a29037e1f629a6f.
